import * as React from "react"
import Fade from 'react-reveal/Fade'
import Slide from 'react-reveal/Slide'

// Components
import Layout from "../components/layout/layout"
import ByTheNumbers from "../components/by-the-numbers/by-the-numbers"
import NumberBlock from "../components/number-block/number-block"

const IndexPage = () => {
  return (
    <Layout>
      <Fade>
        <div className="flex-block">
        <NumberBlock
          numBlockNumber="200"
          numBlockCaption="organizations supported through in-kind donations, volunteerism, or financial support"
        />
        <NumberBlock
          numBlockNumber="56,646"
          numBlockCaption="people impacted by charitable funding or volunteerism"
        />
        <NumberBlock
          numBlockNumber="6,500"
          numBlockCaption="volunteer hours served"
        />
        <NumberBlock
          numBlockNumber={[<><sup>$</sup>176,800</>]}
          numBlockCaption={[<>value of volunteer hours<sup>1</sup></>]}
        />
        <NumberBlock
          numBlockNumber={[<><sup>$</sup>142,345</>]}
          numBlockCaption="generated by employee fundraising"
        />
        <NumberBlock
          numBlockNumber={[<><sup>$</sup>3,207,818</>]}
          numBlockCaption="invested by the company through financial or in-kind donations or distributions from the Rhode Island Community Health Fund at the RI Foundation."
        />
      </div>
      </Fade>
      <ByTheNumbers/>
    </Layout>
  )
}

export default IndexPage
